name: slack-pseudobot
description: A Slack bot that turns members' text into Markov chains.
version: 0.0.1
homepage: https://github.com/seanmccleary/slack-pseudobot
author: Sean McCleary <sean.mccleary@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: ^1.0.0
  shelf_bind: ^0.9.4
  logging: ^0.11.3+1
  http: ^0.11.3+14
  offthechain:
    git: git@github.com:seanmccleary/offthechain.git
  dddart:
    git: git@github.com:seanmccleary/dddart.git

#dev_dependencies:
#  test: ^0.12.0
